// <auto-generated />
using System;
using GoVote.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoVote.Migrations.CandidateDatabase
{
    [DbContext(typeof(CandidateDatabaseContext))]
    [Migration("20200112174337_CandidateDb1")]
    partial class CandidateDb1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GoVote.Data.Candidate", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PartyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VotingTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            ID = new Guid("a756d18e-ce73-49bf-bfde-f7cb7c118ab8"),
                            FirstName = "Klaus",
                            LastName = "Iohannis",
                            PartyID = new Guid("eb14b17c-23ee-42d6-8b8f-8c1569c71900"),
                            VotingTypeId = new Guid("8254d087-4ad7-4069-816f-5ed97d119716")
                        },
                        new
                        {
                            ID = new Guid("fc8fdef0-2f59-42d2-8427-6e0f8e1824ca"),
                            FirstName = "Dan",
                            LastName = "Barna",
                            PartyID = new Guid("37545b86-03be-41c0-b99c-64642b028073"),
                            VotingTypeId = new Guid("8254d087-4ad7-4069-816f-5ed97d119716")
                        },
                        new
                        {
                            ID = new Guid("194ce01d-c4d5-4874-b10c-b70180e86a51"),
                            FirstName = "Viorica",
                            LastName = "Dancila",
                            PartyID = new Guid("87956373-a20e-4c9a-b6db-e62ed99308eb"),
                            VotingTypeId = new Guid("8254d087-4ad7-4069-816f-5ed97d119716")
                        },
                        new
                        {
                            ID = new Guid("0c83870a-b849-44b7-87a8-ffba02643bc2"),
                            FirstName = "Mircea",
                            LastName = "Diaconu",
                            PartyID = new Guid("a6d6c337-d870-4fd7-829d-c5bb240c68b5"),
                            VotingTypeId = new Guid("8254d087-4ad7-4069-816f-5ed97d119716")
                        },
                        new
                        {
                            ID = new Guid("c8d81a12-ed50-4144-b0c8-222f2bf26fa5"),
                            FirstName = "Theodor",
                            LastName = "Paleologul",
                            PartyID = new Guid("e5a072d9-06f5-4fab-88c9-7a1f6c8cb062"),
                            VotingTypeId = new Guid("8254d087-4ad7-4069-816f-5ed97d119716")
                        },
                        new
                        {
                            ID = new Guid("4574f5f7-2ad4-4a36-ac7d-88b29f09b6db"),
                            FirstName = "Kelemen",
                            LastName = "Hunor",
                            PartyID = new Guid("a7dd53e5-0ed5-443d-a8f6-c3cedab4feb0"),
                            VotingTypeId = new Guid("8254d087-4ad7-4069-816f-5ed97d119716")
                        },
                        new
                        {
                            ID = new Guid("7c6b51db-10ea-4d90-a3cf-57a8638f8c94"),
                            FirstName = "Ramona",
                            LastName = "Ioana",
                            PartyID = new Guid("eb14b17c-23ee-42d6-8b8f-8c1569c71900"),
                            VotingTypeId = new Guid("ae040cc6-c820-4f54-8173-0510907c04ee")
                        },
                        new
                        {
                            ID = new Guid("98345799-73c4-4514-96b6-cd76e8b6cbc6"),
                            FirstName = "Catalin",
                            LastName = "Ivan",
                            PartyID = new Guid("cdf668b2-911d-49f6-998d-e212f1b054f8"),
                            VotingTypeId = new Guid("ae040cc6-c820-4f54-8173-0510907c04ee")
                        },
                        new
                        {
                            ID = new Guid("9a98bede-04d3-4a50-80e2-6fb6c6c3bcc1"),
                            FirstName = "Alexandru",
                            LastName = "Cumpanasu",
                            PartyID = new Guid("b0d619d7-f409-4fdc-9e7c-e8fc780e2e31"),
                            VotingTypeId = new Guid("ae040cc6-c820-4f54-8173-0510907c04ee")
                        },
                        new
                        {
                            ID = new Guid("4cd5e71a-957f-4a69-9a7a-17205bbb037f"),
                            FirstName = "Viorel",
                            LastName = "Catarama",
                            PartyID = new Guid("10b098a5-cbbf-4d7a-9e9c-4b50639e5ca4"),
                            VotingTypeId = new Guid("ae040cc6-c820-4f54-8173-0510907c04ee")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
