// <auto-generated />
using System;
using GoVote.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoVote.Migrations
{
    [DbContext(typeof(CitizenDatabaseContext))]
    [Migration("20200112165624_CitizenDbb")]
    partial class CitizenDbb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GoVote.Data.Citizen", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VotedFor")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("Citizens");

                    b.HasData(
                        new
                        {
                            ID = new Guid("8a114780-173b-4ca9-915a-bd26bad53fa0"),
                            Address = "Prelungirea Salciei nr 11",
                            CNP = "6000611068050",
                            City = "Bacau",
                            County = "Bacau",
                            FirstName = "Andreea",
                            LastName = "Rindasu",
                            Sex = "Female",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("f819dce8-54c6-42c8-a2aa-ca0876b1fe6e"),
                            Address = "Trandafirilor nr 19",
                            CNP = "2940306114529",
                            City = "Iasi",
                            County = "Iasi",
                            FirstName = "Andreea",
                            LastName = "Arsene",
                            Sex = "Female",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("038bc0be-604f-43d2-961c-69908d926bfa"),
                            Address = "Mihai Eminesu nr 1",
                            CNP = "1880904084673",
                            City = "Roman",
                            County = "Roman",
                            FirstName = "Matei",
                            LastName = "Lipan",
                            Sex = "Male",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("86779329-1dbe-4eb5-8d9d-82e647fbfb6a"),
                            Address = "Republicii nr 14",
                            CNP = "2861123273951",
                            City = "Suceava",
                            County = "Suceava",
                            FirstName = "Ana",
                            LastName = "Tiganescu",
                            Sex = "Female",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("3c527fd5-1efd-4ff6-8c62-57c5aff428bd"),
                            Address = "Tudor Vladimirescu nr 12",
                            CNP = "2850429512165",
                            City = "Vaslui",
                            County = "Vaslui",
                            FirstName = "Bianca",
                            LastName = "Ciuraru",
                            Sex = "Female",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("04d6341e-8a3a-4273-afd2-8de18e65c14e"),
                            Address = "Mihai Balcesu nr 3",
                            CNP = "6000428269851",
                            City = "Neamt",
                            County = "Neamt",
                            FirstName = "Stefania",
                            LastName = "Andries",
                            Sex = "Female",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("afc01f73-569a-4db2-9472-b510102b77d8"),
                            Address = "Trandafirilor nr 2",
                            CNP = "2960325371467",
                            City = "Roman",
                            County = "Roman",
                            FirstName = "Irina",
                            LastName = "Cercel",
                            Sex = "Female",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("b6cdbb7d-0b9f-4a2c-ba99-9a2aef2b76b0"),
                            Address = "Primaverii nr 3",
                            CNP = "1901109433987",
                            City = "Roman",
                            County = "Roman",
                            FirstName = "Mihnea",
                            LastName = "Rezmerita",
                            Sex = "Male",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("cf558522-425d-4185-9084-ecdd21382fde"),
                            Address = "Libertatii nr 3",
                            CNP = "2920729465763",
                            City = "Neamt",
                            County = "Neamt",
                            FirstName = "Ana-Maria",
                            LastName = "Turcu",
                            Sex = "Female",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("c47a3c32-bd72-42d2-b97a-f51e4267603f"),
                            Address = "Libertatii nr 3",
                            CNP = "1910311156287",
                            City = "Neamt",
                            County = "Neamt",
                            FirstName = "Cristian",
                            LastName = "Vararu",
                            Sex = "Male",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("bf0f0dee-6628-400f-8d86-07a79d87c717"),
                            Address = "Garii nr 134",
                            CNP = "2981127050438",
                            City = "Roman",
                            County = "Roman",
                            FirstName = "Andreea",
                            LastName = "Vatamanelu",
                            Sex = "Female",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("2f97490c-498f-4643-85e9-28b83ce459da"),
                            Address = "Florilor nr 21",
                            CNP = "5000421196666",
                            City = "Harghita",
                            County = "Harghita",
                            FirstName = "Matei",
                            LastName = "Cioata",
                            Sex = "Male",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("7de21f2d-f92b-427e-9134-76d794c0ad6f"),
                            Address = "1 Mai nr 45",
                            CNP = "2960309425462",
                            City = "Suceava",
                            County = "Suceava",
                            FirstName = "Ramona",
                            LastName = "Nechita",
                            Sex = "Female",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("f1b9bfb0-9458-4e48-87b2-a85e1dd94e6f"),
                            Address = "Unirii nr 654",
                            CNP = "6000811408722",
                            City = "Iasi",
                            County = "Iasi",
                            FirstName = "Irina",
                            LastName = "Bejan",
                            Sex = "Female",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("04caa65c-3f6b-4b0b-b7e1-a4afb85359a9"),
                            Address = "Liliacului nr 44",
                            CNP = "2941219407433",
                            City = "Cluj",
                            County = "Cluj",
                            FirstName = "Maria",
                            LastName = "Hlusneac",
                            Sex = "Female",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("bd119af8-21e6-4ceb-bb7d-40fb787d3e63"),
                            Address = "George Cosbuc nr 233",
                            CNP = "1880328521060",
                            City = "Botosani",
                            County = "Botosani",
                            FirstName = "Constantin",
                            LastName = "Listar",
                            Sex = "Male",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("50bae3ad-8255-4592-aa79-e2ca19da0b2f"),
                            Address = "Zorilor nr 77",
                            CNP = "2960807266344",
                            City = "Cluj",
                            County = "Cluj",
                            FirstName = "Simona",
                            LastName = "Spinu",
                            Sex = "Female",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("791daf04-0a6d-4174-9169-3f8a72a6895d"),
                            Address = "Viilor nr 455",
                            CNP = "1910604085307",
                            City = "Bacau",
                            County = "Bacau",
                            FirstName = "Cristian",
                            LastName = "Dragomir",
                            Sex = "Male",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("37108fc2-60a0-4b24-886c-d40bc365757b"),
                            Address = "Vasile Alecsandri nr 23",
                            CNP = "2880406141584",
                            City = "Bucuresti",
                            County = "Bucuresti",
                            FirstName = "Ramona",
                            LastName = "Turcu",
                            Sex = "Female",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("39a92bac-5413-455a-82db-4aba628bb238"),
                            Address = "Pacii nr 45",
                            CNP = "2890724113425",
                            City = "Iasi",
                            County = "Iasi",
                            FirstName = "Dumitrina",
                            LastName = "Aruxandei",
                            Sex = "Female",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("bf8450ae-bc9c-4f05-83b1-494e68b58c26"),
                            Address = "Tineretului nr 2",
                            CNP = "6020719379362",
                            City = "Bucuresti",
                            County = "Bucuresti",
                            FirstName = "Denisa",
                            LastName = "Atomei",
                            Sex = "Female",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("529c30bf-029f-40b8-ae87-42003c9ee081"),
                            Address = "Plopilor nr 3",
                            CNP = "1850821461879",
                            City = "Cluj",
                            County = "Cluj",
                            FirstName = "Daniel",
                            LastName = "Popescu",
                            Sex = "Male",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("a01b5096-b60a-4ae5-9bb9-24e13cd3a396"),
                            Address = "Pacii nr 46",
                            CNP = "2860814180133",
                            City = "Oradea",
                            County = "Oradea",
                            FirstName = "Amalia",
                            LastName = "Andriescu",
                            Sex = "Female",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("229a3cc0-3723-429c-b4b8-068ae8d7902a"),
                            Address = "Aurel Vlaicu nr 345",
                            CNP = "1931127108323",
                            City = "Brasov",
                            County = "Brasov",
                            FirstName = "Nicu",
                            LastName = "Stefanoaia",
                            Sex = "Male",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("8dc919d2-5538-46ad-a1bd-b3783180ebab"),
                            Address = "Crinului nr 66",
                            CNP = "2990119284775",
                            City = "Botosani",
                            County = "Botosani",
                            FirstName = "Ana",
                            LastName = "Gusa",
                            Sex = "Female",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("31f1ca3d-9b98-47f6-824a-b0d9a29f73d7"),
                            Address = "Oituz nr 28",
                            CNP = "1890901434640",
                            City = "Vaslui",
                            County = "Vaslui",
                            FirstName = "Adrian",
                            LastName = "Ionescu",
                            Sex = "Male",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("fb574366-bf4b-419a-a1b5-9831d6375fcb"),
                            Address = "Plopilor nr 754",
                            CNP = "1860217392218",
                            City = "Brasov",
                            County = "Brasov",
                            FirstName = "Ion",
                            LastName = "Ursaciuc",
                            Sex = "Male",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("801ae241-3f27-4d1c-a99b-33c7c9984f1f"),
                            Address = "Tatarasi nr 898",
                            CNP = "1870531383849",
                            City = "Iasi",
                            County = "Iasi",
                            FirstName = "Alex",
                            LastName = "Vulpe",
                            Sex = "Male",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("2ed7bf41-226c-40ed-941c-067184a6ed27"),
                            Address = "Nicu Gane nr 4",
                            CNP = "6020721248923",
                            City = "Suceava",
                            County = "Suceava",
                            FirstName = "Alina",
                            LastName = "Ciobanu",
                            Sex = "Female",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            ID = new Guid("b4cd4a0e-e171-4fef-99a7-352bae76331b"),
                            Address = "George Balcescu nr 7",
                            CNP = "1920212194589",
                            City = "Bacau",
                            County = "Bacau",
                            FirstName = "Lucian",
                            LastName = "Ciulei",
                            Sex = "Male",
                            VotedFor = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
